trunk/beek-admin/src/main/java/co/beek/pano/model/dao/entities/Scene.java
package co.beek.pano.model.dao.entities;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.UploadedFile;

import flexjson.JSON;

@Entity
@Table(name = "scenes")
public class Scene implements Serializable {
	private static final long serialVersionUID = 1L;

	public static enum SceneStatus {
		NEW(0), PENDING_APPROVAL(1), REJECTED(2), CHANGE_REQUESTED(3), ACCEPTED(
				4), CANCELLED(5);

		private int status;

		private SceneStatus(int status) {
			this.status = status;
		}

		public int getStatus() {
			return status;
		}
	}
	
	public static int THUMB_SQUARE = 200;

	@Id
	@Column(name = "id")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private String id;

	@Column(name = "location_id")
	private String locationId;

	@NotNull
	@Column(name = "type")
	private int type;

	@NotNull
	@Column(name = "status")
	private int status;
	
	@NotNull
	@Column(name = "latitude")
	private double latitude;

	@NotNull
	@Column(name = "longitude")
	private double longitude;

	@NotNull
	@Column(name = "zoom")
	private int zoom;

	@NotNull
	@Column(name = "thumbincrement")
	private int thumbIncrement;

	@NotNull
	@Column(name = "panoincrement")
	private int panoIncrement;

	@Size(max = 255)
	@Column(name = "title")
	private String title;

	@Lob
	@Column(name = "description")
	private String description;

	@Lob
	@Column(name = "comments")
	private String comments;

	@NotNull
	@Column(name = "fov")
	private int fov;

	@NotNull
	@Column(name = "tilt")
	private int tilt;

	@NotNull
	@Column(name = "pan")
	private int pan;

	@NotNull
	@Column(name = "north")
	private int north;

	@Size(max = 200)
	@Column(name = "bookingurl")
	private String bookingURL;

	@Size(max = 200)
	@Column(name = "infourl")
	private String infoURL;
	
	@Column(name = "voiceover")
	private String voiceover;


	@Column(name = "video")
	private String video;


	@NotNull
	@Column(name = "is_default", columnDefinition = "TINYINT")
	private boolean isDefault;

	@NotNull
	@Column(name = "is_uploaded", columnDefinition = "TINYINT")
	private boolean isUploaded;

	@ManyToOne()
	@Fetch(value = FetchMode.JOIN)
	@JoinColumn(name = "location_id", insertable = false, updatable = false)
	private Location location;


	public Scene() {
	}
	
	public Scene(Location location) {
		locationId = location.getId();
		type = location.getType();
		latitude = location.getLatitude();
		longitude = location.getLongitude();
	}


	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public int getType() {
		return type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public double getLatitude() {
		return latitude;
	}

	public void setLatitude(double latitude) {
		this.latitude = latitude;
	}

	public double getLongitude() {
		return longitude;
	}

	public void setLongitude(double longitude) {
		this.longitude = longitude;
	}

	public int getZoom() {
		return zoom;
	}

	public void setZoom(int zoom) {
		this.zoom = zoom;
	}

	public int getThumbIncrement() {
		return thumbIncrement;
	}

	public void setThumbIncrement(int thumbIncrement) {
		this.thumbIncrement = thumbIncrement;
	}

	public void incrementThumb() {
		this.thumbIncrement++;
	}

	public void incrementPano() {
		this.panoIncrement++;
	}

	public int getPanoIncrement() {
		return panoIncrement;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getFov() {
		return fov;
	}

	public void setFov(int fov) {
		this.fov = fov;
	}

	public int getTilt() {
		return tilt;
	}

	public void setTilt(int tilt) {
		this.tilt = tilt;
	}

	public int getPan() {
		return pan;
	}

	public void setPan(int pan) {
		this.pan = pan;
	}

	public int getNorth() {
		return north;
	}

	public void setNorth(int north) {
		this.north = north;
	}

	public String getBookingURL() {
		return bookingURL;
	}

	public void setBookingURL(String bookingURL) {
		this.bookingURL = bookingURL;
	}

//	public String getInfoURL() {
//		return infoURL;
//	}

	public void setInfoURL(String infoURL) {
		this.infoURL = infoURL;
	}

	@JSON(include = false)
	public Location getLocation() {
		return location;
	}
	
	public String getLocationTitle() {
		return location.getTitle();
	}
	
	public String getEmail() {
		return location.getEmail();
	}
	
	public String getPhone() {
		return location.getPhone();
	}
	
	public String getinfoURL() {
		return location.getInfoURL();
	}
	

	public void setLocation(Location location) {
		this.location = location;
	}

	public String getLocationId() {
		return locationId;
	}

	public void setLocationId(String locationId) {
		this.locationId = locationId;
	}
	
	public String getVoiceover() {
		return voiceover;
	}

	public void setVoiceover(String voiceover) {
		this.voiceover = voiceover;
	}

	public String getVideo() {return video;}

	public void setVideo(String video) {this.video = video;}

	public String getThumbName() {
		return "scene_" + id + "_thumb_" + thumbIncrement + ".jpg";
	}

	public String getPanoPrefix() {
		return "scene_" + id + "_pano_" + panoIncrement;
	}

	public String getPanoName() {
		return getPanoPrefix() + ".jpg";
	}


	public boolean isDefault() {
		return isDefault;
	}

	public void setDefault(boolean isDefault) {
		this.isDefault = isDefault;
	}

	public boolean isUploaded() {
		return true;
	}

	public void setUploaded(boolean isUploaded) {
		this.isUploaded = isUploaded;
	}


	@Override
	public int hashCode() {
		int hash = 0;
		hash += (id != null ? id.hashCode() : 0);
		return hash;
	}

	@Override
	public boolean equals(Object object) {
		if (!(object instanceof Scene)) {
			return false;
		}
		Scene other = (Scene) object;
		if ((this.id == null && other.id != null)
				|| (this.id != null && !this.id.equals(other.id))) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "Scene[ id=" + id + " ]";
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public void toggleapproval(){status = status == 0 ? 1 : 0;}

	public int getStatus() {
		return status;
	}
	
	/**
	 * I know that this is not done right.
	 * Need to figure out how to use enums.
	 * @return
	 */
	public String getStatusText() {
		if(status == Scene.SceneStatus.NEW.getStatus())
			return "New";

		if(status == Scene.SceneStatus.ACCEPTED.getStatus())
			return "Accepted";

		if(status == Scene.SceneStatus.REJECTED.getStatus())
			return "Regected";

		if(status == Scene.SceneStatus.CHANGE_REQUESTED.getStatus())
			return "Changes Requested";
		
		return "Other Status";
	}

	public void setComments(String value) {
		this.comments = value;
	}

	/**
	 * The changes that are populated in the wizard, but not persisted in the
	 * database or serialized and sent to the client in json.
	 * 
	 * @return
	 */
	@JSON(include = false)
	public String getComments() {
		return comments;
	}

	@Transient
	private UploadedFile uploadedFile;

	public void handleFileUpload(FileUploadEvent event) {
		uploadedFile = event.getFile();
	}

	@JSON(include = false)
	public UploadedFile returnUpload() {
		return uploadedFile;
	}
}

trunk/beek-admin/src/main/java/co/beek/web/guide/GuideViewController.java
package co.beek.web.guide;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map.Entry;

import javax.inject.Inject;
import javax.servlet.http.HttpServletRequest;

import org.apache.commons.lang.StringUtils;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import co.beek.Constants;
import co.beek.pano.model.dao.entities.Beek;
import co.beek.pano.model.dao.entities.Guide;
import co.beek.pano.model.dao.entities.GuideDetail;
import co.beek.pano.model.dao.entities.GuideScene;
import co.beek.pano.model.dao.entities.GuideSection;
import co.beek.pano.service.dataService.BeekService;
import co.beek.pano.service.dataService.FavouritesService;
import co.beek.pano.service.dataService.guideService.GuideService;
import co.beek.web.BaseController;
import flexjson.JSONSerializer;

@Controller("GuideViewController")
@Scope("session")
public class GuideViewController extends BaseController implements Serializable {
	private static final long serialVersionUID = 897552663451118806L;

	JSONSerializer serializer = new JSONSerializer().prettyPrint(true);

	private Beek beek;

	private Guide guide;
	
	private GuideDetail selectedGuide;

	private GuideScene selectedScene;
	
	private String connectId;



	private String userId;
	
	private String hotspotId;

	@Inject
	private GuideService guideService;

	@Inject
	private BeekService beekService;

	@Inject
	private FavouritesService favouritesService;

	private HashMap<String, String> flashVars;

	@Value("#{buildProperties.gaCode}")
	private String gaCode;

	@Value("#{buildProperties.cdnUrl}")
	private String cdnUrl;

	@RequestMapping(value = "/guide/{guideId}/view", method = RequestMethod.GET)
	public String map(HttpServletRequest request,
			@PathVariable("guideId") String guideId) {
		return "/views/guide/view.jsf?g=" + guideId + "&e="
				+ request.getParameter("email");
	}
	
	@RequestMapping(value = "/subdomain/{guidename}/", method = RequestMethod.GET)
	public String mapSubdomain(HttpServletRequest request,
			@PathVariable("guidename") String guidename) throws Exception {
			List <Guide> guides = guideService.getGuideBySubdomain(guidename);
			if(guides.isEmpty())
				throw new Exception("this is no guide");
			Guide guide = guides.get(0);
			String id = guide.getId();
		return "/views/guide/view.jsf?g=" + id + "&e="
				+ request.getParameter("email");
	}

	@RequestMapping(value = "/guide/{guideId}/scene/{sceneId}", method = RequestMethod.GET)
	public String mapView1(@PathVariable("guideId") String guideId,
			@PathVariable("sceneId") String sceneId) {
		return "/views/guide/view.jsf?g=" + guideId + "&s=" + sceneId;
	}

	@RequestMapping(value = "/guide/{guideId}/scene/{sceneId}/hotspot/{hotspotId}", method = RequestMethod.GET)
	public String mapView2(@PathVariable("guideId") String guideId,
			@PathVariable("sceneId") String sceneId,
			@PathVariable("hotspotId") String hotspotId) {
		return "/views/guide/view.jsf?g=" + guideId + "&s=" + sceneId + "&h="
				+ hotspotId;
	}
	
	@RequestMapping(value = "/guide/{guideId}/scene/{sceneId}/connect/{cId}", method = RequestMethod.GET)
	public String mapView3(@PathVariable("guideId") String guideId,
			@PathVariable("sceneId") String sceneId,
			@PathVariable("cId") String connectId) {
		return "/views/guide/view.jsf?g=" + guideId + "&s=" + sceneId + "&c="
				+ connectId;
	}

	@RequestMapping(value = "/guide/{guideId}/scene/{sceneId}/visit/{visitId}", method = RequestMethod.GET)
	public String mapView4(@PathVariable("guideId") String guideId,
						   @PathVariable("sceneId") String sceneId,
						   @PathVariable("visitId") String visitId) {
			return "/views/guide/view.jsf?g=" + guideId + "&s=" + sceneId + "&v="
                    + visitId;
	}

	public void validateGuideViewPageURL() throws Exception {
		HttpServletRequest request = getRequest();

		// Get the beek data
		beek = beekService.getBeek();

		if (Constants.domain == null)
			throw new Exception("Please visit the login page");

		String guideId = request.getParameter("id");
		if (guideId == null || guideId.equals(""))
			guideId = request.getParameter("g");

		selectedGuide = guideService.getGuideDetail(guideId);
		if (selectedGuide == null)
			throw new Exception("Guide not found");

		selectedScene = null;

		String sceneId = request.getParameter("s");
		if (sceneId != null && !sceneId.equals(""))
			selectedScene = selectedGuide.returnScene(sceneId);

		if (selectedScene == null)
			selectedScene = selectedGuide.returnFirstScene();

		connectId = request.getParameter("c");

		userId = request.getParameter("v");

		flashVars = new HashMap<String, String>();
		flashVars.put("domain", Constants.domain);
		flashVars.put("assetCdn", cdnUrl);
		flashVars.put("adminSwf", getAdminSwfUrl());
		flashVars.put("gaCode", gaCode);
		flashVars.put("hotspotId", hotspotId);
		flashVars.put("userId", userId);
		flashVars.put("connectId", connectId);

		if (selectedGuide != null) {
			flashVars.put("guideId", selectedGuide.getId());
			flashVars.put("hideotherguides",
					selectedGuide.isOtherguides() ? "false" : "true");
		}

		if (selectedScene != null)
			flashVars.put("sceneId", selectedScene.getScene().getId());

		if (getSession(request).getUser() != null)
			flashVars.put("autologin", "true");
	}

	public GuideDetail getSelectedGuide() {
		return selectedGuide;
	}
	
	public List<GuideSection> getSelectedGuideSections() {
		List<GuideSection> temp = new ArrayList<GuideSection>();
		for(GuideSection section : selectedGuide.getGuideSections())
			if(section.parent_section_id == null)
				temp.add(section);
		
		return temp;
	}

	public void setSelectedGuide(GuideDetail selectedGuide) {
		this.selectedGuide = selectedGuide;
	}

	public GuideScene getSelectedScene() {
		return selectedScene;
	}

	public String getUserId() {return userId;}

	public void setUserId(String userId) {this.userId = userId;}
	
	public String getHotspotId() {
		return hotspotId;
	}

	public String getDomain() {
		return Constants.domain;
	}


	public String getPlayerSwfUrl() {
		if (Constants.domain.contains("beekdev.co"))
			return "http://gms.beekdev.co/resources/swf/swf_player.swf";

		return cdnUrl + "/" + beek.getPlayerFileName();
	}

	public String getAdminSwfUrl() {
		if (Constants.domain.contains("beekdev.co"))
			return "http://gms.beekdev.co/resources/swf/swf_admin.swf";

		return cdnUrl + "/" + beek.getAdminFileName();
	}

	public String getScenePath() {
		if (selectedScene != null)
			return getGuidePath() + "/s" + selectedScene.getScene().getId();

		return getGuidePath();
	}

	public String getGuidePath() {
		if (selectedGuide != null)
			return "/g" + selectedGuide.getId();

		return "";
	}
	
	public String getConnectId() {
		return connectId;
	}
	
	public String getGuideTitleURl() {
		if (selectedGuide != null)
			return selectedGuide.getTitle().replace(' ', '-');

		return "";
	}
	
	public String getGuideSceneURl() {
		if (selectedGuide != null)
			return selectedGuide.getTitle().replace(' ', '-');

		return "";
	}

	/**
	 * Returns a comma delimted version of the flash vars
	 * 
	 * @return
	 */
	public String getFlashVarsCD() {
		List<String> props = new ArrayList<String>();

		Iterator<Entry<String, String>> it = flashVars.entrySet().iterator();
		while (it.hasNext()) {
			Entry<String, String> prop = it.next();
			props.add(prop.getKey() + "=" + prop.getValue());
		}
		return StringUtils.join(props, "&");
	}

	public String getFlashVarsJSON() {
		return serializer.serialize(flashVars);
	}

	public String getGuideNamesCommaDelimited() {
		List<String> props = new ArrayList<String>();

		List<GuideSection> sections = selectedGuide.getGuideSections();
		for (GuideSection section : sections) {
			for (GuideScene scene : section.getGuideScenes())
				props.add(scene.getTitleMerged());
		}
		return StringUtils.join(props, ", ");
	}
}

trunk/beek-admin/src/main/webapp/views/scene/edit.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
				xmlns:h="http://java.sun.com/jsf/html"
				xmlns:f="http://java.sun.com/jsf/core"
				xmlns:c="http://java.sun.com/jsp/jstl/core"
				xmlns:ui="http://java.sun.com/jsf/facelets"
				xmlns:p="http://primefaces.org/ui">

<html xmlns="http://www.w3.org/1999/xhtml"
	  xmlns:h="http://java.sun.com/jsf/html"
	  xmlns:f="http://java.sun.com/jsf/core">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<f:metadata>
	<f:event listener="#{SceneController.preRenderView}" type="preRenderView"/>
</f:metadata>

	<style type="text/css" media="screen">

		html, body {
			height: 100%;
			overflow: hidden;
			font-family: Arial, Helvetica, sans-serif;
		}

		body {
			margin: 0;
			padding: 0;
			text-align: center;
			layout: absolute;
		}

		.preview-visible {
			margin: 0;
			padding: 0;
			height: 100%;
			width: 100%;
		}

		.preview-hidden {
			display:none;
			visibility:hidden;
			height: 1px;
			width: 1px;
		}

		#preloadtext {
			text-align: left;
		}

		#preloader {
			display: none;
			width: 200px; /*the width of the element*/
			height: 100px; /*the height of the element*/
			position: absolute; /*absolute position to center the element in relation to its parent element*/
			left: 50%; /*the left border of the element is positioned at half of the available width of the parent element*/
			top: 50%; /*the top border of the element is positioned at half of the available height of the parent element*/
			margin-left: -100px; /*half of the element width is removed from the left margin to center it*/
			margin-top: -50px; /*half of the element height is removed from the top margin to center it*/
		}

		#preloadtrack {
			width:200px;
			background-color:#999999;
			padding:2px;
		}
		#preloadbar {
			width:1px;
			height:10px;
			background-color:#CCC;
		}

		#preview img {
			width: 100%;
			height: auto;
			position: absolute;
			left: 0;
			opacity:0;
			filter:alpha(opacity='0');
			Filter:Blur(Add = 0, Direction = 225, Strength = 5);
			z-index:-1;
		}

		#play-button {
			display: none;
		}

		#itunes-button {
			display: none;
		}

		.flash-hidden {
			display: none;
			height: 1px;
			width: 1px;
		}

		.flash-visible {
			height: 100%;
			width: 100%;
		}
	</style>

	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js"></script>
	<script type="application/javascript">

		var loadImmediately = false;
		var flashLoaded = false;

		var STAGE_SWF_LOADED = 1;
		var STAGE_GUIDE_LOADED = 2;
		var STAGE_SCENE_LOADED = 3;


		function showPreloader()
		{
			document.getElementById("preloader").style.display = "block";
			document.getElementById("preloader").style.visibility = "visible";
			showProgress(0.2);
		}

		function preloadFlash()
		{
			showPreloader();

			// fail safe in-case the thumb does not load.
			setTimeout("loadFlash()", 1000);

			loadImmediately = true;
		}

		function onPlayButtonClick()
		{
			document.getElementById("play-button").style.display = "none";
			document.getElementById("play-button").style.visibility = "hidden";

			showPreloader();
			loadFlash();
		}

		function loadFlash()
		{
			if(flashLoaded)
				return;
			flashLoaded = true;

			showProgress(0.2);

			var swfVersionStr = "10.2.0";
			var xiSwfUrlStr = "/resources/swf/playerProductInstall.swf";
			var flashvars = #{SceneController.flashVarsJson};

			var params = {
				"quality" : "high",
				"bgcolor" : "#ffffff",
				"allowscriptaccess" : "always",
				"allowfullscreen" : "true",
				"wmode" : "direct"
			}

			var attributes = {};
			attributes.id = "player-swf";
			attributes.name = "player-swf";
			attributes.align = "top";

			var playerVersion = swfobject.getFlashPlayerVersion();
			var swfUrl = playerVersion.major &lt; 11
					? "#{SceneController.playerSwfUrlFlash10}"
					: "#{SceneController.playerSwfUrl}?r=asdf";

			swfobject.embedSWF(
					swfUrl,
					"player-div",
					"100%", "100%",
					swfVersionStr,
					xiSwfUrlStr,
					flashvars,
					params,
					attributes
			);
		}


		var fadeEffect=function(){
			return{
				init:function(id, flag, target){
					this.elem = document.getElementById(id);
					clearInterval(this.elem.si);
					this.target = target ? target : flag ? 100 : 0;
					this.flag = flag || -1;
					this.alpha = this.elem.style.opacity ? parseFloat(this.elem.style.opacity) * 100 : 0;
					this.si = setInterval(function(){fadeEffect.tween()}, 20);
				},
				tween:function(){
					if(this.alpha == this.target){
						clearInterval(this.si);
					}else{
						var value = Math.round(this.alpha + ((this.target - this.alpha) * .05)) + (1 * this.flag);
						this.elem.style.opacity = value / 100;
						this.elem.style.filter = 'alpha(opacity=' + value + ')';
						this.alpha = value
					}
				}
			}
		}();

		function getWindowHeight()
		{
			var winW = 630, winH = 460;
			if (document.body &amp;&amp; document.body.offsetWidth) {
				winW = document.body.offsetWidth;
				winH = document.body.offsetHeight;
			}
			if (document.compatMode=='CSS1Compat' &amp;&amp;
					document.documentElement &amp;&amp;
					document.documentElement.offsetWidth ) {
				winW = document.documentElement.offsetWidth;
				winH = document.documentElement.offsetHeight;
			}
			if (window.innerWidth &amp;&amp; window.innerHeight) {
				winW = window.innerWidth;
				winH = window.innerHeight;
			}

			return winH;
		}

		function onThumbLoaded()
		{
			var thumb = document.getElementById("preloadthumb");
			var headerHeight = 35;
			thumb.style.left = "0";
			thumb.style.top = (getWindowHeight() - thumb.height)/2 + headerHeight +"px";

			fadeEffect.init('preloadthumb', 1, 100);


			if(loadImmediately)
				loadFlash();
		}

		var currpercent = 0;
		var timeout;

		function showProgress(percent, endfunction)
		{
			currpercent += 0.02;

			document.getElementById("preloadtext").innerHTML = (percent *100)+"% loaded";
			var track = document.getElementById("preloadtrack");
			var bar = document.getElementById("preloadbar");
			var curr_width = parseInt(track.style.width);

			bar.style.width = (200 * currpercent) + "px";

			if(currpercent &lt; percent)
				timeout = setTimeout("showProgress("+percent+", "+endfunction+");", 20);

			else if(endfunction != null)
				endfunction();
		}

		function showFlash()
		{
			clearTimeout(timeout);

			showProgress(1, setSwfVisible);
		}

		function setSwfStage(stage)
		{
			switch(stage)
			{
				case STAGE_SWF_LOADED:
					showProgress(0.5);
					break;

				case STAGE_GUIDE_LOADED:
					showProgress(0.7);
					break;

				case STAGE_SCENE_LOADED:
					showFlash();
					break;
			}
		}

		function setSwfVisible()
		{
			document.getElementById("preview").className = "preview-hidden";
			//document.getElementById("player-div").className = "flash-visible";

			//document.getElementById("player-swf").width = "100%;";
			//document.getElementById("player-swf").height = "100%;";
		}



	</script>
</head>
<body>


		<div id="preview" class="preview-visible" >
			<img id="preloadthumb" onload="onThumbLoaded()" src="#{buildProperties.cdnUrl}/#{SceneController.scene.thumbName}" />
			<div id="preloader">
				<div id="preloadtext">this is some text</div>
				<div id="preloadtrack"><div id="preloadbar"></div></div>
			</div>
		</div>
		<div id="player-div" class="flash-hidden">
			<p>
				To view this page ensure that Adobe Flash Player version
				10.2.0 or greater is installed.
			</p>
			<script type="text/javascript">
				var pageHost = ((document.location.protocol == "https:") ? "https://" : "http://");
				document.write(unescape("%3Ca href='http://www.adobe.com/go/getflashplayer'%3E%3Cimg src='" + pageHost + "www.adobe.com/images/shared/download_buttons/get_flash_player.gif' alt='Get Adobe Flash player'/%3E"));
			</script>
		</div>

<script type="text/javascript">
		preloadFlash();
</script>
</body>
</html>
</ui:composition>