trunk/beek-admin/src/main/java/co/beek/pano/model/dao/entities/Location.java
package co.beek.pano.model.dao.entities;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.Immutable;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import co.beek.pano.model.dao.enterprizewizard.EWPhotoShoot;

@Entity
@Table(name = "locations")
public class Location implements Serializable {
	private static final long serialVersionUID = 1L;

	/**
	 * Photoshoots that have been accepted, and are in the 'process' stage
	 */
	public static int STATE_NEW = 0;

	/**
	 * Locations that have been through the 'process' stage, and are awaiting
	 * approval.
	 */
	public static int STATE_PENDING = 1;

	/**
	 * Locations that have been approved.
	 */
	public static int STATE_LIVE = 2;

	/**
	 * Locations that have been cancelled.
	 */
	public static int STATE_CANCELLED = 3;

	public static int LOGO_SQUARE = 130;



	@Id
	@Column(name = "id")
	@GeneratedValue(strategy = GenerationType.AUTO)
	private String id;

	@NotNull
	@Column(name = "team_id")
	private String teamId;

	@Column(name = "order_id")
	private String photoShootId;

	@Column(name = "ew_id")
	private String ewId;

	@NotNull
	@Column(name = "sceneordercount")
	private int sceneOrderCount;



	@NotNull
	@Column(name = "sceneapprovedcount")
	private int sceneApprovedCount;

	@NotNull
	@Column(name = "scenecount")
	private int sceneCount;

	@NotNull
	@Column(name = "status")
	private int status;

	@NotNull
	@Column(name = "type")
	private int type;

	@NotNull
	@Column(name = "destination_id")
	private String destinationId;

	@Column(name = "default_scene_id", insertable = true, updatable = true)
	private String defaultSceneId;

	//@Column(name = "logo_file_id", insertable = true, updatable = true)
	//private long logoFileId;

	@NotNull
	@Column(name = "latitude")
	private double latitude;

	@NotNull
	@Column(name = "longitude")
	private double longitude;

	@Size(max = 255)
	@Column(name = "title")
	public String title;

	@Lob
	@Column(name = "description")
	private String description;

	/**
	 * Comments that came from photoshoot
	 */
	@Lob
	@Column(name = "comments")
	private String comments;
//
	@Size(max = 100)
	@Column(name = "infourl")
	private String infoURL;

	@Size(max = 100)
	@Column(name = "bookingurl")
	private String bookingURL;

	// @Pattern(regexp="^\\(?(\\d{3})\\)?[- ]?(\\d{3})[- ]?(\\d{4})$",
	// message="Invalid phone/fax format, should be as xxx-xxx-xxxx")//if the
	// field contains phone or fax number consider using this annotation to
	// enforce field validation
	@Size(max = 100)
	@Column(name = "phone")
	private String phone;

	// @Pattern(regexp="[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?",
	// message="Invalid email")//if the field contains email address consider
	// using this annotation to enforce field validation
	@Size(max = 100)
	@Column(name = "email")
	private String email;
//
//	@Size(max = 200)
//	@Column(name = "address")
//	private String address;

	@Immutable
	@ManyToOne()
	@Fetch(value = FetchMode.JOIN)
	@NotFound(action = NotFoundAction.IGNORE)
	@Cascade({ org.hibernate.annotations.CascadeType.MERGE })
	@JoinColumn(name = "default_scene_id", insertable = false, updatable = false)
	private Scene defaultScene;

//	@ManyToOne()
//	@Fetch(value = FetchMode.JOIN)
//	@NotFound(action = NotFoundAction.IGNORE)
//	@Cascade({ org.hibernate.annotations.CascadeType.MERGE })
//	@JoinColumn(name = "logo_file_id", insertable = false, updatable = false)
//	private FileData logoFile;

	/**
	 * Making this insertable/updatable means that i can save location/scenes in
	 * one go with hibernate when processing an order
	 */
	// @OneToMany(cascade = CascadeType.ALL)
	// @JoinColumn(name = "location_id", insertable = true, updatable = true)
	// private List<Scene> scenes = new ArrayList<Scene>();

	public Location() {
	}

	/**
	 * Constructor when creating a scene from an order.
	 */
	public Location(Destination destination, EWPhotoShoot shoot) {
		setDestination(destination);
		setPhotoShoot(shoot);

	}

	public void setDestination(Destination destination) {
		destinationId = destination.getId();
		latitude = destination.getLatitude();
		longitude = destination.getLongitude();
	}

	public void setPhotoShoot(EWPhotoShoot shoot) {
		teamId = shoot.getTeamId();
		photoShootId = shoot.getId();
		title = shoot.getLocationTitle();
		comments = shoot.getComments();
		sceneOrderCount = shoot.getSceneOrderCount();
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public int getType() {
		return type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public double getLatitude() {
		return latitude;
	}

	public void setLatitude(double latitude) {
		this.latitude = latitude;
	}

	public double getLongitude() {
		return longitude;
	}

	public void setLongitude(double longitude) {
		this.longitude = longitude;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getInfoURL() {
		return infoURL;
	}

	public void setInfoURL(String infoURL) {
		this.infoURL = infoURL;
	}

	public String getBookingURL() {
		return bookingURL;
	}

	public void setBookingURL(String bookingURL) {
		this.bookingURL = bookingURL;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

//	public String getAddress() {
//		return address;
//	}
//
//	public void setAddress(String address) {
//		this.address = address;
//	}

	// @JSON(include = false)
	// public List<Scene> getScenes() {
	// return scenes;
	// }
	//
	// public void addScene(Scene scene) {
	// scenes.add(scene);
	//
	// // update this each time scene is added
	// sceneCount = scenes.size();
	//
	// if(sceneCount == 1)
	// {
	// defaultScene = scene;
	// defaultSceneId = scene.getId();
	// }
	// }

	// @JSON(include = false)
	// public HashMap<Long, String> getSceneLookup() {
	// HashMap<Long, String> lookup = new HashMap<Long, String>();
	// for (Scene scene : scenes) {
	// lookup.put(scene.getId(), scene.getTitle());
	// }
	// return lookup;
	// }
	//
	// public void setScenes(List<Scene> scenes) {
	// this.scenes = scenes;
	// }

//	public FileData getLogoFile() {
//		return logoFile;
//	}
//
//	public void setLogoFile(FileData logoFile) {
//		this.logoFileId = logoFile.getId();
//		this.logoFile = logoFile;
//	}

	public Scene getDefaultScene() {
		return defaultScene;
	}

	public void setDefaultScene(Scene defaultScene) {
		this.defaultScene = defaultScene;
	}

	public String getDestinationId() {
		return destinationId;
	}

	public void setDestinationId(String destinationId) {
		this.destinationId = destinationId;
	}

	public String getDefaultSceneId() {
		return defaultSceneId;
	}

	public void setDefaultSceneId(String defaultSceneId) {
		this.defaultSceneId = defaultSceneId;
	}

//	public long getLogoFileId() {
//		return logoFileId;
//	}
//
//	public void setLogoFileId(long logoFileId) {
//		this.logoFileId = logoFileId;
//	}

	@Override
	public int hashCode() {
		int hash = 0;
		hash += (id != null ? id.hashCode() : 0);
		return hash;
	}

	@Override
	public boolean equals(Object object) {
		if (!(object instanceof Location)) {
			return false;
		}
		Location other = (Location) object;
		if ((this.id == null && other.id != null)
				|| (this.id != null && !this.id.equals(other.id))) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "Location[ id=" + id + " ]";
	}

	public void setTeamId(String teamId) {
		this.teamId = teamId;
	}

	public String getTeamId() {
		return teamId;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getComments() {
		return comments;
	}

	public String getPhotoShootId() {
		return photoShootId;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getStatus() {
		return status;
	}

	public String getStatusText() {
		if (status == Location.STATE_NEW)
			return "New";

		if (status == Location.STATE_PENDING)
			return "Pending Approval";

		if (status == Location.STATE_LIVE)
			return "Live";

		if (status == Location.STATE_CANCELLED)
			return "Cancelled";

		return "Other Status";
	}

	public void setSceneCount(int sceneCount) {
		this.sceneCount = sceneCount;
	}

	public int getSceneCount() {
		return sceneCount;
	}

	public int getSceneOrderCount() {
		return sceneOrderCount;
	}


	public int getSceneApprovedCount() {
		return sceneApprovedCount;
	}

	public void setSceneApprovedCount(int sceneApprovedCount) {
		this.sceneApprovedCount = sceneApprovedCount;
	}

	public String getEwId() {
		return ewId;
	}

	public void setEwId(String ewId) {
		this.ewId = ewId;
	}
}

trunk/beek-admin/src/main/java/co/beek/web/location/LocationCreateController.java
package co.beek.web.location;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.servlet.http.HttpServletRequest;

import org.primefaces.context.RequestContext;
import org.primefaces.event.FlowEvent;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import co.beek.pano.model.beans.LocationMapModel;
import co.beek.pano.model.dao.enterprizewizard.EWContact;
import co.beek.pano.model.dao.enterprizewizard.EWCreateResponse;
import co.beek.pano.model.dao.entities.Destination;
import co.beek.pano.model.dao.entities.Location;
import co.beek.pano.model.dao.entities.Scene;
import co.beek.pano.service.dataService.enterprizewizardService.EWService;
import co.beek.pano.service.dataService.locationService.LocationService;
import co.beek.pano.service.dataService.sceceService.SceneService;
import co.beek.util.BeekSession;
import co.beek.web.BaseController;

@Scope("session")
@Controller("LocationCreateController")
public class LocationCreateController extends BaseController implements
        Serializable {
    private static final long serialVersionUID = -1081621548447371624L;

    @Inject
    private LocationService locationService;

    @Inject
    private SceneService sceneService;

    private Location location;

    private LocationMapModel locationMapModel;

    private List<Scene> scenes;

    @Inject
	public EWService ewService;

    @RequestMapping(value = "/location/create", method = RequestMethod.GET)
    public String mapView() {
        return "/views/location/create.jsf";
    }

    public void preRenderView() throws IOException {
        if (redirectingToLogin())
            return;

        if (isPostback())
            return;

        BeekSession session = getSession();
        EWContact contact = session.getUser();

        location = new Location();
        location.setStatus(Location.STATE_NEW);
        location.setTitle("New Location");
        location.setTeamId("CUSTOMER_1_");
        location.setDestinationId("1");
        //TODO make the teams work/take them out
        //location.setTeamId(contact.getTeams().get(0).getTeams());
        //location.setDestination(1);

        locationMapModel = new LocationMapModel(location);

        scenes = new ArrayList<Scene>();
    }

    public Location getLocation() {
        return location;
    }

    public LocationMapModel getLocationMapModel() {
        return locationMapModel;
    }

    public List<Destination> getDestinations() {
        return getSession().getDestinations();
    }

    public void handleDestinationChange() {
        Destination destination = getDestination(location.getDestinationId());
        location.setDestination(destination);
    }

    public String onFlowProcess(FlowEvent event) throws IOException {
        // Must save before adding scenes
        if (event.getOldStep().equals("locationTab")){
            locationService.saveLocation(location);
        	processSubmit();
        }

        if (event.getOldStep().equals("scenesTab")) {
            reloadScenesFromDB();

            if (event.getNewStep().equals("finishTab")) {
                if (scenes.size() > 0) {
                    location.setSceneCount(scenes.size());
                    location.setDefaultSceneId(scenes.get(0).getId());
                   // locationService.saveLocation(location);
                    
                    
                    
                } else {
                    // Stop progress if they have not created any scenes
                    showError("You must add at least one scene.");
                    return event.getOldStep();
                }
            }
        }
        return event.getNewStep();
    }

    private void reloadScenesFromDB() {
        this.scenes = sceneService.getAllScenesForLocation(location.getId());
        RequestContext.getCurrentInstance().update("scenesTab");
    }

    public List<Scene> getScenes() {
        return scenes;
    }

    public void addScene() {
        HttpServletRequest req = (HttpServletRequest)FacesContext.getCurrentInstance().getExternalContext().getRequest();

        String sceneName = req.getParameter("sceneName");
        String sceneId = req.getParameter("sceneId");

        if(sceneId == null || sceneId.equals("")){
            return;
        }

        Scene scene = new Scene(location);

        if(sceneName == null || sceneName.equals("")){
            scene.setTitle("NEW SCENE");
        }else{
            scene.setTitle(sceneName);
        }

        scene = sceneService.saveScene(scene);
        scenes.add(scene);

        if (scenes.size() == 1) {
            location.setSceneCount(scenes.size());
            location.setDefaultSceneId(scenes.get(0).getId());
            locationService.saveLocation(location);
        }

        // pass the data back for javascript access
        RequestContext context = RequestContext.getCurrentInstance();
        context.addCallbackParam("temp_sceneId", sceneId);
        context.addCallbackParam("sceneId", scene.getId());
        context.addCallbackParam("sceneName", scene.getTitle());
    }

    private Destination getDestination(String destinationId) {
        List<Destination> destinations = getSession().getDestinations();
        for (Destination destination : destinations)
            if (destination.getId().equals(destinationId))
                return destination;

        return null;
    }

    public Scene getDefaultScene() {
        if (location.getDefaultSceneId() != null)
            return sceneService.getScene(location.getDefaultSceneId());

        return null;
    }

    public void processSubmit() throws IOException {
        //location.setStatus(Location.STATE_LIVE);
        // default scene has changed, submit
        location.setDestinationId("1");
        location.setTeamId("CUSTOMER_1_");
        locationService.saveLocation(location);
        BeekSession session = getSession();
        EWContact user = session.getUser();
        List<String> updateLocationID = session.getLocationID();
        updateLocationID.add(location.getId());
        session.setLocationID(updateLocationID);
        user.setLocationID(updateLocationID);
        saveLocationToCRM();

        redirectLocationEdit(location.getId());
    }
    
    
	private void saveLocationToCRM()
	{

        EWCreateResponse response = null;
		try {

            response = ewService.createLocation(getSession().getUsername(), getSession().getPassword(), location);
			location.setEwId(response.getResult());
            locationService.saveLocation(location);

		} catch (Exception e) {
			FacesMessage m2 = new FacesMessage(FacesMessage.SEVERITY_ERROR,
					"Location Failed", "There was an error saving this location to the CRM: " + e.getMessage());
			FacesContext.getCurrentInstance().addMessage(null, m2);
		}
		
	}
}

trunk/beek-admin/src/main/webapp/views/location/OnlyGMap.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:c="http://java.sun.com/jsp/jstl/core"
                template="../template.xhtml">
    <ui:define name="checkurl">
	    <f:metadata>
	        <f:event listener="#{LocationCreateController.preRenderView}" 
	        		type="preRenderView"/>
	    </f:metadata>
	</ui:define>
	
	<ui:param name="location" value="#{LocationCreateController.location}" />
	<ui:define name="script">
	    <h:outputScript library="js" name="accordion.js"/>
	</ui:define>
	<ui:define name="gmap">
        <script src="http://maps.google.com/maps/api/js?sensor=false" type="text/javascript"></script>
        <h:outputScript library="js" name="map-service.js"/>
        <script type="text/javascript">
		  function showFlash(accordionId)
		  {
			var activeIndex = $("#"+accordionId+"_active").val();
			var visibleTab = $("#"+accordionId+"\\:" + activeIndex + "\\:scene_tab");
			var holder = visibleTab.find('#flash_holder');
			
			// Populate iframe if not already
			if(holder.html() == "" || holder.html() == null)
				holder.html(
					'&lt;iframe src="'+holder.attr("iframeurl")+'" class="sceneAccordionTab" width="100%" height"100%" scrolling="no" /&gt;'
				);
		  }
		  
		  function resetAllAccordions()
		  {
		  	  resetAccordionPanel('scenesAccordionId');
		  }
		  
		  function resetAccordionPanel(accordionId)
		  {
		  	   // A hidden field in the accordion that stores the current active index
		  	   $('#'+accordionId+'_active').val(-1);
		  }
           
          function onAddSceneComplete(xhr, status, args) {
		      var sceneId = args.sceneId;
		      var content = '&lt;div id="flash_holder" iframeurl="/views/scene/view.jsf?s='+sceneId+'&amp;autologin=true" class="sceneAccordionTab" scrolling="no" &gt;&lt;/div&gt;';
		      scenesAccordionVar.addTabHtml(content);
		  }
        </script>
    </ui:define>
    
    <ui:define name="content">
						  <tr>
					    	<td valign="top">
					    		<br/>
						    	<p:outputPanel id="map_panel"> 
							        <p:gmap id="location_map"
			                                widgetVar="l_map"
			                                type="ROADMAP"
			                                draggable="true"
			                                style="width:610px;height:300px"
			                                onPointClick="addMarker(event,PF('l_map'));return false;"
			                                zoom="13"
			                                model="#{LocationCreateController.locationMapModel}"
			                                center="#{location.latitude},#{location.longitude}">
			                                <p:ajax event="stateChange" listener="#{LocationCreateController.locationMapModel.onStateChange}"/>
			                                <p:ajax event="pointSelect" listener="#{LocationCreateController.locationMapModel.onPointSelect}"/>
			                                <p:ajax event="markerDrag" listener="#{LocationCreateController.locationMapModel.onMarkerDrag}"/>
			                        </p:gmap>
									<script type="text/javascript">
									   function setLocationMarker()
									   {
									   		if(PF('l_map'))
										   		updateMarker(
										   			'#{location.latitude}',
										   			'#{location.longitude}',
										   			'13',
										   			PF('l_map')
										   		);
									   }
									   setTimeout(setLocationMarker, 1000);
									</script>
					             </p:outputPanel> 
						    </td>
						  </tr>
    	</ui:define>
</ui:composition>

trunk/beek-admin/src/main/webapp/views/location/dashboard.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:c="http://java.sun.com/jsp/jstl/core"
                template="../newtemplate.xhtml">

    <ui:define name="checkurl">
        <f:metadata>
            <f:event listener="#{LocationDashboardController.preRenderView}"
                     type="preRenderView"/>
        </f:metadata>

    </ui:define>
    <ui:define name="content">
    <h:head>

 <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
 <title>Location Dashboard</title>
 <script type="text/javascript" src="http://maps.google.com/maps/api/js?v=3"></script>
 <script type="text/javascript" src="/resources/js/label.js"></script>
 <script type="text/javascript" src="/resources/js/markerclusterer.js"></script>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>Beek Admin Console</title>
    <h:outputStylesheet library="css" name="style.css"/>
    <ui:insert name="gmap"/>
    <ui:insert name="script"/>
    <ui:insert name="checkAccess">
        <f:metadata>
            <f:event listener="#{TemplateController.isLoggedIn()}" type="preRenderView"/>
    </f:metadata>
    </ui:insert>
</h:head>


<h:body onload="initialize(#{LocationDashboardController.getMapLocationsTitles()}, #{LocationDashboardController.getMapLats()}, #{LocationDashboardController.getMapLons()}, #{LocationDashboardController.getMapLocationIDs()})">

    <div style="margin-left:5%; margin-right:5%">
    	<h:form>
    	
    	<p:commandButton value="New Location" icon="ui-icon-plus" style="font-weight: bold; width:150px; margin-left:1%;"
	                  action="#{LocationDashboardController.goToCreateLocation()}"/>
		<p:commandButton value="Search" icon="ui-icon-search" style="width:80px; float:right; margin-right: 8px"
	                  action="#{LocationDashboardController.searchButton()}" />
	    <p:inputText id="searchTerm"  value="#{LocationDashboardController.searchTerm}" style="width:200px; margin-right: 8px; margin-top: 4px; float:right"/>

         <p:commandButton value="Show all" icon="ui-icon-refresh" style="width:120px; margin-right: 50px; float:right"
	                  action="#{LocationDashboardController.showAllLocationsButton()}"/>
		</h:form>
        <div id="pagetitle" align="left">
        
            <ui:insert name="pagetitle"/>
        </div>
    
    <div id="footer">
    
        <ui:insert name="footer" />
    </div>
 <div id="map_canvas" style="height: 800px; width: 100%"></div>
 <br/><br/>

 </div>
</h:body>
 </ui:define>

</ui:composition>

trunk/beek-admin/src/main/webapp/views/location/view.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="../template.xhtml">

	<ui:define name="checkurl">
	    <f:metadata>
	        <f:event listener="#{LocationViewController.preRenderView}" type="preRenderView"/>
	    </f:metadata>
	</ui:define>
	
    
	<ui:define name="content">
		<p:breadCrumb>
			<p:menuitem value="Dashboard" url="/" />
			<p:menuitem value="Location - #{LocationViewController.location.statusText}" url="/location/#{LocationViewController.location.id}/view" />
		</p:breadCrumb>
		
		<script type="text/javascript">
          var prevHolder;
		  function showFlash(accordionId)
		  {
		  	if(prevHolder != null)
		  		prevHolder.html("");
		  	
		  	
			var activeIndex = $("#"+accordionId+"_active").val();
			var visibleTab = $("#"+accordionId+"\\:" + activeIndex + "\\:scene_tab");
			var holder = visibleTab.find('#flash_holder');
			holder.html(
				'&lt;iframe src="'+holder.attr("iframeurl")+'" style="'+holder.attr("style")+'" width="100" height"100" /&gt;'
			);
			
			prevHolder = holder;
		  }
        </script>
        
		<center>
			<p:accordionPanel id="scenesAccordion" 
				value="#{LocationViewController.scenes}"
				var="scene"
				cache="true"
				activeIndex="-1"
				onTabShow="showFlash('scenesAccordion')">
				<p:tab id="scene_tab" title="#{scene.title}" >
					<table width="900" border="1">
					  <tr>
					    <td width="450">
					    	<div id="flash_holder" 
					    		iframeurl="/scene/#{scene.id}/view" 
					    		style="width:450px; height:340px">
					    	</div>
					    </td>
					    <td valign="top">
					    	Status: <h:outputText value="#{scene.statusText}" /><br/>
					    	<h:outputText value="#{scene.comments}" />
					    </td>
					  </tr>
					</table>
				</p:tab>
			</p:accordionPanel>
		</center>
	</ui:define>
</ui:composition>