trunk/beek-admin/src/main/java/co/beek/web/shoot/PhotoShootController.java
package co.beek.web.shoot;

import java.io.Serializable;
import java.util.List;

import javax.inject.Inject;
import javax.servlet.http.HttpServletRequest;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import co.beek.pano.model.dao.enterprizewizard.EWContact;
import co.beek.pano.model.dao.enterprizewizard.EWPhotoShoot;
import co.beek.pano.model.dao.enterprizewizard.EWPhotoShootResponse;
import co.beek.pano.model.dao.enterprizewizard.EWPhotoShootsResponse;
import co.beek.pano.model.dao.enterprizewizard.EWTeam;
import co.beek.pano.service.dataService.enterprizewizardService.EWService;
import co.beek.util.BeekSession;
import co.beek.web.BaseController;

@Scope("session")
@Controller("PhotoShootController")
public class PhotoShootController extends BaseController implements
		Serializable {
	private static final long serialVersionUID = -1081621548447371624L;

	@Inject
	private EWService ewService;

	private EWPhotoShoot photoShoot;

	@RequestMapping(value = "/shoot/{id}/view", method = RequestMethod.GET)
	public String mapView(@PathVariable("id") long id) {
		return "/views/shoot/view.jsf?id=" + id;
	}

	public void preRenderView() throws Exception {
		HttpServletRequest request = getRequest();
		if (!isLoggedIn(request)) {
			redirectLogin(request);
			return;
		}

		String photoShootId = request.getParameter("id");
		photoShoot = getPhotoShoot(photoShootId);

		if (photoShoot == null)
			throw new Exception("Photoshoot not found");
	}

	private EWPhotoShoot getPhotoShoot(String shootId) throws Exception {
		BeekSession session = getSession();
		List<EWPhotoShoot> photoShoots = session.getPhotoShoots();
		if (photoShoots == null)
			photoShoots = loadPhotoShoots(session);

		for (EWPhotoShoot shoot : photoShoots)
			if (shoot.getId().equals(shootId))
				return shoot;

		return null;
	}

	private List<EWPhotoShoot> loadPhotoShoots(BeekSession session)
			throws Exception {
		EWPhotoShootsResponse photoShootsResponse = ewService.queryPhotoShoots(
				session.getUsername(), session.getPassword());
		List<EWPhotoShoot> photoShoots = photoShootsResponse.getPhotoShoots();
		session.setPhotoShoots(photoShoots);

		return photoShoots;
	}

	public EWPhotoShoot getPhotoShoot() {
		return photoShoot;
	}

	public void acceptPhotoShoot() {
		try {
			acceptPhotoShoot(photoShoot);
			redirectHome();

		} catch (Exception e) {
			sendErrorDan("Error accepting photo shoot", e);
			showError("There has been an error accepting this photo shoot. "
					+ "Beek has been notified of the problem.");
		}
	}

	private void acceptPhotoShoot(EWPhotoShoot photoShoot) throws Exception {
		BeekSession session = getSession();
		EWPhotoShootResponse response = ewService.updatePhotoShootState(
				session.getUsername(), session.getPassword(),
				photoShoot.getId(),
				EWPhotoShoot.PhotoShootStatus.ACCEPTED.getCode());

		if (response.getSuccess()) {
			photoShoot = response.getPhotoShoot();

			// update our cached photoShoots
			updateShootInSession(photoShoot);

			// update the teams for htis user
			updateTeamsInSession(photoShoot);

			showMessage("Photo Shoot Accepted",
					"The photoShoot " + photoShoot.getLocationTitle()
							+ " has been accepted.");
		} else {
			throw new Exception(response.getErrorMessage());
		}
	}

	private void updateTeamsInSession(EWPhotoShoot photoShoot) {
		// The photographer is added to this team automatically.
		EWContact user = getUser();
		if (!user.isInTeam(photoShoot.getTeamId()))
			user.addTeam(new EWTeam(photoShoot.getTeamId()));
	}

	private void updateShootInSession(EWPhotoShoot photoShoot) {
		List<EWPhotoShoot> photoShoots = getSession().getPhotoShoots();
		for (int i = 0; i < photoShoots.size(); i++)
			if (photoShoots.get(i).getId().equals(photoShoot.getId()))
				photoShoots.set(i, photoShoot);
	}

	public void declinePhotoShoot() {
		try {
			declinePhotoShoot(photoShoot);
			redirect("/");

		} catch (Exception e) {
			sendErrorDan("Error declining photo shoot", e);
			showError("There has been an error declining this photo shoot. "
					+ "Beek has been notified of the problem.");
		}
	}

	private void declinePhotoShoot(EWPhotoShoot photoShoot) throws Exception {
		BeekSession session = getSession();
		EWPhotoShootResponse response = ewService.updatePhotoShootState(
				session.getUsername(), session.getPassword(),
				photoShoot.getId(),
				EWPhotoShoot.PhotoShootStatus.DECLINED.getCode());
		if (response.getSuccess()) {
			photoShoot = response.getPhotoShoot();
			// update our cached photoShoots
			updateShootInSession(photoShoot);
			showMessage("PhotoShoot Declined",
					"The photoShoot " + photoShoot.getLocationTitle()
							+ " has been declined.");
		} else {
			// show the error message
			throw new Exception(response.getErrorMessage());
		}
	}

	public void processPhotoShoot() {
		try {
			// Location location = processPhotoShoot(photoShoot);
			redirect("/shoot/" + photoShoot.getId() + "/process");
		} catch (Exception e) {
			sendErrorDan("Error processing photo shoot", e);
			showError("There has been an error processing this photo shoot. "
					+ "Beek has been notified of the problem.");
		}
	}
}

trunk/beek-admin/src/main/java/co/beek/web/shoot/PhotoShootProcessController.java
package co.beek.web.shoot;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map.Entry;

import javax.inject.Inject;
import javax.servlet.http.HttpServletRequest;

import org.primefaces.context.RequestContext;
import org.primefaces.event.FlowEvent;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import co.beek.pano.model.beans.LocationMapModel;
import co.beek.pano.model.dao.enterprizewizard.EWPhotoShoot;
import co.beek.pano.model.dao.enterprizewizard.EWPhotoShootResponse;
import co.beek.pano.model.dao.enterprizewizard.EWPhotoShootsResponse;
import co.beek.pano.model.dao.enterprizewizard.EWTeam;
import co.beek.pano.model.dao.entities.Destination;
import co.beek.pano.model.dao.entities.Location;
import co.beek.pano.model.dao.entities.Scene;
import co.beek.pano.service.dataService.destinationService.DestinationService;
import co.beek.pano.service.dataService.enterprizewizardService.EWService;
import co.beek.pano.service.dataService.locationService.LocationService;
import co.beek.pano.service.dataService.sceceService.SceneService;
import co.beek.util.BeekSession;
import co.beek.web.BaseController;

@Scope("session")
@Controller("PhotoShootProcessController")
public class PhotoShootProcessController extends BaseController implements
		Serializable {
	private static final long serialVersionUID = -1081621548447371624L;

	@Inject
	private LocationService locationService;

	@Inject
	private SceneService sceneService;

	@Inject
	private DestinationService destinationService;
	
	@Inject
	private EWService ewService;

	private EWPhotoShoot photoShoot;

	private Location location;

	private LocationMapModel locationMapModel;

	private List<Scene> scenes;

	private String message;

	@RequestMapping(value = "/shoot/{id}/process", method = RequestMethod.GET)
	public String mapView(@PathVariable("id") long id) {
		return "/views/shoot/process.jsf?id=" + id;
	}

	public void preRenderView() throws Exception {
		if (isPostback())
			return;

		if (redirectingToLogin())
			return;

		String photoShootId = getRequest().getParameter("id");
		photoShoot = getShootFromSession(photoShootId);

		if (photoShoot == null)
			throw new Exception("Photoshoot not found");

		System.out.println(photoShoot.getTeamId());
		getUser().addTeam(new EWTeam(photoShoot.getTeamId()));

		if (!getUser().isInTeam(photoShoot.getTeamId()))
			throw new Exception("Cannot edit photoshoot, is not on team: "
					+ photoShoot.getTeamId() + ". This team should have "
					+ "been added to the user when the photoshoot was Accepted");

		Destination destination = destinationService
				.getDestinationByTitle(photoShoot.getDestination());

		Location existing = locationService.getLocationForOrder(photoShootId);
		if (existing != null) {
			location = existing;
			scenes = sceneService.getAllScenesForLocation(location.getId());
		} else {
			location = new Location(destination, photoShoot);
			scenes = null;
		}

		locationMapModel = new LocationMapModel(location);
	}

	private EWPhotoShoot getShootFromSession(String shootId) throws Exception {
		BeekSession session = getSession();
		List<EWPhotoShoot> photoShoots = session.getPhotoShoots();
		if (photoShoots == null)
			photoShoots = loadPhotoShoots(session);

		for (EWPhotoShoot shoot : photoShoots)
			if (shoot.getId().equals(shootId))
				return shoot;

		return null;
	}

	private List<EWPhotoShoot> loadPhotoShoots(BeekSession session)
			throws Exception {
		EWPhotoShootsResponse photoShootsResponse = ewService.queryPhotoShoots(
				session.getUsername(), session.getPassword());
		List<EWPhotoShoot> photoShoots = photoShootsResponse.getPhotoShoots();
		session.setPhotoShoots(photoShoots);

		return photoShoots;
	}

	public Location getLocation() {
		return location;
	}

	public LocationMapModel getLocationMapModel() {
		return locationMapModel;
	}

	public List<Scene> getScenes() {
		return scenes;
	}

	public int getNumScenes() {
		if (scenes != null)
			return scenes.size();

		return photoShoot.getEwScenes().size();
	}

	public String onFlowProcess(FlowEvent event) {
		if (event.getOldStep().equals("locationTab"))
			createScenesFromPhotoshoot();

		if (event.getOldStep().equals("scenesTab"))
			reloadScenesFromDB();

		return event.getNewStep();
	}

	private void reloadScenesFromDB() {
		this.scenes = sceneService.getAllScenesForLocation(location.getId());
		RequestContext.getCurrentInstance().update("scenesTab");
	}

	private void createScenesFromPhotoshoot() {
		try {

			locationService.saveLocation(location);

			// Create the scenes if they have not already
			if (scenes == null)
				scenes = convertPhotoShootScenes(photoShoot, location);

			if (scenes.size() > 0)
				setDefaultScene(location, scenes);

		} catch (Exception e) {
			sendErrorDan("Error saving the scenes for photoshoot: "
					+ photoShoot.getId(), e);
			showError("There has been an error saving the scenes from this photoshoot. "
					+ "Beek has been notified of the problem.");
		}
	}

	private List<Scene> convertPhotoShootScenes(EWPhotoShoot photoShoot,
			Location location) {
		List<Scene> scenes = new ArrayList<Scene>();
		HashMap<String, HashMap<String, String>> ews = photoShoot.getEwScenes();
		Iterator<Entry<String, HashMap<String, String>>> it = ews.entrySet()
				.iterator();
		while (it.hasNext()) {
			HashMap<String, String> ewScene = it.next().getValue();
			Scene scene = new Scene(location);
			scene.setTitle(ewScene.get("scene_name"));

			// save the scene in db.
			scene = sceneService.saveScene(scene);

			// add the new scene to the list
			scenes.add(scene);
		}

		return scenes;
	}

	public void addScene() {
		Scene scene = new Scene(location);
		scene.setTitle("NEW SCENE");
		scene = sceneService.saveScene(scene);
		scenes.add(scene);

		location.setSceneCount(scenes.size());

		// pass the data back for javascript access
		RequestContext context = RequestContext.getCurrentInstance();
		context.addCallbackParam("sceneId", scene.getId());
	}

	private void setDefaultScene(Location location, List<Scene> scenes) {
		// update default scene id after scenes are inserted
		Scene firstScene = scenes.get(0);
		location.setSceneCount(scenes.size());
		location.setDefaultSceneId(firstScene.getId());
	}

	public Scene getDefaultScene() {
		if (location.getDefaultSceneId() != null)
			return sceneService.getScene(location.getDefaultSceneId());

		return null;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getMessage() {
		return message;
	}

	public void requestApproval() {
		try {
			HttpServletRequest request = getRequest();

			String approvalUrl = "http://" + request.getServerName()
					+ "/location/" + location.getId() + "/wizard";

			BeekSession session = getSession(request);
			EWPhotoShootResponse response = ewService.requestApproval(
					session.getUsername(), session.getPassword(),
					location.getPhotoShootId(),
					EWPhotoShoot.PhotoShootStatus.PROCESSED.getCode(),
					approvalUrl, message);

			if (!response.getSuccess())
				throw new Exception("Error response from EW: "
						+ response.getErrorMessage());

			location.setStatus(Location.STATE_PENDING);
			location.setSceneCount(scenes.size());
			locationService.saveLocation(location);

			showMessage("Approval Requested",
					"The location " + location.getTitle()
							+ " has been sent to the owner for approval.");
			redirectHome();

		} catch (Exception e) {
			sendErrorDan("Error requesting approval", e);
		}

	}

}

trunk/beek-admin/src/main/webapp/views/shoot/process.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:c="http://java.sun.com/jsp/jstl/core"
                template="../template.xhtml">
                
    <ui:param name="location" value="#{PhotoShootProcessController.location}" />
    <ui:param name="locationMapModel" value="#{PhotoShootProcessController.locationMapModel}" />
    
    <ui:define name="checkurl">
	    <f:metadata>
	        <f:event listener="#{PhotoShootProcessController.preRenderView}" 
	        		type="preRenderView"/>
	    </f:metadata>
	</ui:define>
	<ui:define name="script">
	    <h:outputScript library="js" name="accordion.js"/>
	</ui:define>

	<ui:define name="gmap">
        <script src="http://maps.google.com/maps/api/js?sensor=false" type="text/javascript"></script>
        <h:outputScript library="js" name="map-service.js"/>
        <script type="text/javascript">
		  function showFlash(accordionId)
		  {
			var activeIndex = $("#"+accordionId+"_active").val();
			var visibleTab = $("#"+accordionId+"\\:" + activeIndex + "\\:scene_tab");
			var holder = visibleTab.find('#flash_holder');
			
			// Populate iframe if not already
			if(holder.html() == "" || holder.html() == null)
				holder.html(
					'&lt;iframe src="'+holder.attr("iframeurl")+'" class="sceneAccordionTab" width="100" height"100" scrolling="no" /&gt;'
				);
		  }
		  
		  function resetAllAccordions()
		  {
		  	  resetAccordionPanel('scenesAccordionId');
		  }
		  
		  function resetAccordionPanel(accordionId)
		  {
		  	   // A hidden field in the accordion that stores the current active index
		  	   $('#'+accordionId+'_active').val(-1);
		  }
           
          function onAddSceneComplete(xhr, status, args) {
		      var sceneId = args.sceneId;
		      var content = '&lt;div id="flash_holder" iframeurl="/views/scene/view.jsf?s='+sceneId+'&amp;autologin=true" class="sceneAccordionTab" &gt;&lt;/div&gt;';
		      PF('scenesAccordionVar').addTabHtml(content);
		  }
		  
		  function triggerBrowse()
		  {
			  	var logoUploader = $("#logoUploaderId");
			  	var button = logoUploader.find('.fileinput-button');
				button.click();
		  }
        </script>
    </ui:define>

    <ui:define name="content">
		<p:breadCrumb>
			<p:menuitem value="Dashboard" url="/" />
			<p:menuitem value="#{location.title} - Wizard" url="/shoot/#{location.photoShootId}/wizard" />
		</p:breadCrumb>
        <center>
           <h:form id="wizard_form" prependId="false">
				<p:wizard id="locationWizard" widgetVar="wiz" 
						flowListener="#{PhotoShootProcessController.onFlowProcess}"
						onnext="resetAllAccordions()" onprev="resetAllAccordions()">
					<p:tab id="locationTab" title="Details" >
						<p:growl id="uploadedScenesGrowl" showDetail="true" autoUpdate="true"/>
						<p:panel header="Location Details - Status: #{location.statusText}">
							<table width="100%" border="0">
							  <tr>
							    <td valign="top" width="280" >
							    	<h:outputText value="Type: " /><br/>  
									<p:selectOneMenu effect="fade"
		                                 value="#{location.type}"
		                                 style="width:260px">
					                    <f:selectItem itemLabel="Activity" itemValue="1"/>
					                    <f:selectItem itemLabel="Accommodation" itemValue="2"/>
					                    <f:selectItem itemLabel="Attraction" itemValue="3"/>
					                    <f:selectItem itemLabel="Entertainment" itemValue="4"/>
					                    <f:selectItem itemLabel="Restaurant" itemValue="5"/>
					                    <f:selectItem itemLabel="Transportation" itemValue="6"/>
					                    <f:selectItem itemLabel="Venue" itemValue="7"/>
					                </p:selectOneMenu>
                
							    	<h:outputText value="Title: " /><br/>  
				                    <p:inputText label="Title" style="width:260px" 
				                            value="#{location.title}" /><br/>   
				                      
				                    <h:outputText value="Description: " /><br/> 
				                    <p:inputTextarea label="Description"  
				                            value="#{location.description}" 
				                            style="width:260px;height:245px;"/><br/> 
							    </td>
							    <td valign="top">
							        <br/>
								    <p:gmap id="location_map"
                                            widgetVar="l_map"
                                            type="ROADMAP"
                                            draggable="true"
                                            style="width:600px;height:305px; margin-bottom:5px;"
                                            onPointClick="addMarker(event,PF('l_map'));return false;"
                                            zoom="13"
                                            model="#{PhotoShootProcessController.locationMapModel}"
                                            center="#{location.latitude},#{location.longitude}">
                                            <p:ajax event="stateChange" listener="#{PhotoShootProcessController.locationMapModel.onStateChange}"/>
	                                        <p:ajax event="pointSelect" listener="#{PhotoShootProcessController.locationMapModel.onPointSelect}"/>
	                                        <p:ajax event="markerDrag" listener="#{PhotoShootProcessController.locationMapModel.onMarkerDrag}"/>
                                    </p:gmap>
                                    
									<script type="text/javascript">
									   function setLocationMarker()
									   {
									   		if(PF('l_map'))
										   		updateMarker(
										   			'#{location.latitude}',
										   			'#{location.longitude}',
										   			'13',
										   			PF('l_map')
										   		);
									   }
									   
									   setTimeout(setLocationMarker, 1000);
									</script>
									<p:spacer width="300" height="10" />
									<p:inputText id="searchField" style="width:200px; height:18px;"/>
					                <p:commandButton value="Search" ajax="true"
		                                 update="location_map" style="width:90px;height:26px"
		                                 onclick="findLocation(PF('l_map'));return false;"/>
							    </td>
							  </tr>
							</table>
		                </p:panel>
						
					</p:tab>
					<p:tab id="scenesTab" title="Scenes">
						<p:accordionPanel id="scenesAccordionId" 
								widgetVar="scenesAccordionVar"
								value="#{PhotoShootProcessController.scenes}"
								var="scene"
								cache="true"
								activeIndex="-1"
								onTabShow="showFlash('scenesAccordionId')">
								<p:tab id="scene_tab" title="#{scene.title}" css-class="sceneAccordionTab" >
									<div id="flash_holder" class="sceneAccordionTab" scrolling="no"
							    		iframeurl="/views/scene/view.jsf?s=#{scene.id}&amp;autologin=true"></div>
								</p:tab>
						</p:accordionPanel>
                        <p:commandButton value="ADD SCENE" ajax="true" immediate="true"
					        	action="#{PhotoShootProcessController.addScene()}"
					        	oncomplete="onAddSceneComplete(xhr, status, args)"/>
					</p:tab>
					
					<p:tab id="finish" title="Finish">
						<h:panelGrid columns="2">
							<p:outputPanel>
								<h:outputText value="Title: #{location.title}" /><br/> 
			                    	<p:selectOneMenu style="width:190px" 
						                 value="#{location.defaultSceneId}">
			                         <f:selectItems value="#{PhotoShootProcessController.scenes}" 
								                 	var="scene" 
								                    itemLabel="#{scene.title}" 
								                    itemValue="#{scene.id}" />
								     <p:ajax update="default_scene_image" event="change" />
			                      </p:selectOneMenu>
							</p:outputPanel>
							<p:outputPanel>
								<h:outputText value="Send the scenes to the client for approval." /><br/>
								<h:outputText value="Add A message." /><br/>
							</p:outputPanel>
							<p:outputPanel>
			                      <p:outputPanel id="default_scene_image" autoUpdate="true" 
			                      		style="display:block;width:200px;height:200px;background-color:#EFEFEF;">
					                    <p:graphicImage style="display:block;width:200px;height:200px;"
					                    	url="#{buildProperties.cdnUrl}/#{PhotoShootProcessController.defaultScene.thumbName}" />
			                   	  </p:outputPanel>
							</p:outputPanel>
							<p:outputPanel>
								<p:inputTextarea label="Description"  
						                            value="#{message}" 
						                            style="width:260px;height:190px;"/>
							</p:outputPanel>
							<p:outputPanel>
								<br/>
							</p:outputPanel>
							<p:outputPanel>
						        <p:commandButton value="REQUEST APPROVAL" 
						        		ajax="true" immediate="true"
							        	action="#{PhotoShootProcessController.requestApproval()}"/>
							</p:outputPanel>
					    </h:panelGrid>
					</p:tab>
				</p:wizard>
			</h:form>          
        </center>
    </ui:define>
</ui:composition>

trunk/beek-admin/src/main/webapp/views/shoot/view.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:c="http://java.sun.com/jsp/jstl/core"
                template="../template.xhtml">

	<ui:define name="checkurl">
	    <f:metadata>
	        <f:event listener="#{PhotoShootController.preRenderView}" type="preRenderView"/>
	    </f:metadata>
	</ui:define>
    <ui:define name="content">
    
    <p:breadCrumb>
		<p:menuitem value="Dashboard" url="/" />
		<p:menuitem value="PhotoShoot" url="/shoot/#{PhotoShootController.photoShoot.id}" />
	</p:breadCrumb>

    <h:form>
    <p:growl id="info" showDetail="true" autoUpdate="true"/>
    <p:panel header="PhotoShoot Details" id="shootDetails" style="width:800px"> 
	    <table width="700" border="0" >
		  <tr>
		    <td>state</td>
		    <td><h:outputText value="#{PhotoShootController.photoShoot.wfstate}" /></td>
		  </tr>
		  <tr>
		    <td>customer_name</td>
		    <td><h:outputText value="#{PhotoShootController.photoShoot.customer_name}" /></td>
		  </tr>
		  <tr>
		    <td>scene_location</td>
		    <td><h:outputText value="#{PhotoShootController.photoShoot.locationTitle}" /></td>
		  </tr>
		  <tr>
		    <td width="147">shoot_instructions</td>
		    <td width="537"><h:outputText value="#{PhotoShootController.photoShoot.shoot_instructions}" /></td>
		  </tr>
		  <tr>
		    <td>shoot_preferred_date</td>
		    <td><h:outputText value="#{PhotoShootController.photoShoot.dates}" /></td>
		  </tr>
		  <tr>
		    <td>shoot_full_name</td>
		    <td><h:outputText value="#{PhotoShootController.photoShoot.shoot_full_name}" /></td>
		  </tr>
		  <tr>
		    <td>shoot_telephone</td>
		    <td><h:outputText value="#{PhotoShootController.photoShoot.shoot_telephone}" /></td>
		  </tr>
		  <tr>
		    <td>shoot_email</td>
		    <td><h:outputText value="#{PhotoShootController.photoShoot.shoot_email}" /></td>
		  </tr>
		  <tr>
		    <td>shoot_time</td>
		    <td><h:outputText value="#{PhotoShootController.photoShoot.shoot_time}" /></td>
		  </tr>
		  <tr>
		    <td>team</td>
		    <td><h:outputText value="#{PhotoShootController.photoShoot.teamId}" /></td>
		  </tr>
		  <tr>
		    <td>comments</td>
		    <td><h:outputText value="#{PhotoShootController.photoShoot.comments}" /></td>
		  </tr>
		  <tr>
		    <td>num scenes</td>
		    <td><h:outputText value="#{PhotoShootController.photoShoot.numScenes}" /></td>
		  </tr>
		</table>
		<p:dataTable  var="ewScene" width="200"
				value="#{PhotoShootController.photoShoot.scenesMap}" 
		        emptyMessage="No scenes found.">
		
		    <p:column headerText="Name">
		        <h:outputText value="#{ewScene.scene_name}" />
		    </p:column>
		
		    <p:column headerText="Shooting Requirements">
		        <h:outputText value="#{ewScene.shooting_requirements}" />
		    </p:column>
		    
		</p:dataTable>
	    <f:facet name="footer">
		    <ui:fragment rendered='#{PhotoShootController.photoShoot.status == "New"}'>
			    <p:commandButton value="ACCEPT" ajax="true"
					action="#{PhotoShootController.acceptPhotoShoot}"/>
		    </ui:fragment>
		    
		    <ui:fragment rendered='#{PhotoShootController.photoShoot.status == "Assigned"}'>
			    <p:commandButton value="ACCEPT" ajax="true"
					action="#{PhotoShootController.acceptPhotoShoot}"/>
			    <p:commandButton value="DECLINE" ajax="true"
					action="#{PhotoShootController.declinePhotoShoot}"/>
		    </ui:fragment>
		    
		    <ui:fragment rendered='#{PhotoShootController.photoShoot.status == "Accepted"}'>
			    <h:commandButton value="PRINT" type="button" icon="ui-icon-print">  
			        <p:printer target="shootDetails" />  
			    </h:commandButton>
			    <p:commandButton value="PROCESS" ajax="true"
					action="#{PhotoShootController.processPhotoShoot}"/>
		    </ui:fragment>
		    <ui:fragment rendered='#{PhotoShootController.photoShoot.status == "Processed"}'>
			    <p:commandButton value="EDIT" ajax="true"
					action="#{PhotoShootController.processPhotoShoot}"/>
		    </ui:fragment>
	    </f:facet>
	</p:panel>
    
		</h:form>
    </ui:define>
</ui:composition>