trunk/beek-admin/src/main/java/co/beek/pano/model/dao/entities/Guide.java
package co.beek.pano.model.dao.entities;

import java.io.Serializable;
import java.util.Comparator;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import co.beek.pano.model.dao.enterprizewizard.EWContact;
import co.beek.pano.model.dao.enterprizewizard.EWGroup;

class GuideComparator implements Comparator<Guide> {
	public int compare(Guide r1, Guide r2) {
		return (r2.getScore() - r1.getScore());
	}
}

class GuideIdComparator implements Comparator<Guide> {
	public int compare(Guide r1, Guide r2) {
		return (r2.getIdInt() - r1.getIdInt());
	}
}


@Entity
@Table(name = "guides")
public class Guide implements Serializable {

	public static final GuideComparator scoreComparator = new GuideComparator();
	public static final GuideIdComparator idComparator = new GuideIdComparator();

	private static final long serialVersionUID = 1L;

	public static int STATUS_FREE = 0;
	public static int STATUS_PUBLISHED = 1;
	public static int STATUS_PROMOTED = 2;

	@Id
	@Column(name = "id")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private String id = "";

	@NotNull
	@Column(name = "team_id")
	private String teamId;

	@NotNull
	@Column(name = "destination_id")
	private String destinationId;

	@Column(name = "location_id")
	public String locationId;

	@Column(name = "status")
	public int status;

	@Column(name = "otherguides", columnDefinition = "TINYINT")
	private boolean otherguides;

	@Column(name = "title")
	@Size(max = 100, message = "Invalid title(0-100 characters}")
	private String title;

	@Column(name = "description")
	private String description;


	@Column(name = "colormajor")
	@Size(max = 6, message = "Invalid major color(0-6 characters}")
	private String colorMajor;


	@Column(name = "logo_file_id")
	private Long logoFileId;
	
	@Column(name = "coverDesign")
	private String coverDesign;

	@Column(name = "saveincrement")
	public int saveIncrement;

	@Column(name = "thumbincrement")
	private int thumbIncrement;

	@Column(name = "zipincrement")
	public int zipIncrement;

	@Column(name = "pageviews")
	private int pageviews;

	@Column(name = "visits")
	private int visits;

	@Column(name = "time")
	private int time;

	@Column(name = "score")
	private int score;
	
	@Column(name = "subdomain")
	public String subdomain;
	
	@Column(name = "parent")
	public String parent;

	public String getId() {
		return id;
	}
	
	public Integer getIdInt() {
		return Integer.parseInt(id);
	}

	public void setId(String id) {
		this.id = id;
	}

	public void setTeamId(String teamId) {
		this.teamId = teamId;
	}

	public String getTeamId() {
		return teamId;
	}

	/*
	 * public String getDescription() { return description; }
	 * 
	 * public void setDescription(String description) { this.description =
	 * description; }
	 * 
	 * public String getInfoURL() { return infoURL; }
	 * 
	 * public void setInfoURL(String infoURL) { this.infoURL = infoURL; }
	 * 
	 * public String getBookingURL() { return bookingURL; }
	 * 
	 * public void setBookingURL(String bookingURL) { this.bookingURL =
	 * bookingURL; }
	 * 
	 * public String getPhone() { return phone; }
	 * 
	 * public void setPhone(String phone) { this.phone = phone; }
	 * 
	 * public String getEmail() { return email; }
	 * 
	 * public void setEmail(String email) { this.email = email; }
	 * 
	 * public String getAddress() { return address; }
	 * 
	 * public void setAddress(String address) { this.address = address; }
	 */
	
	public String getColorMajor() {
		return colorMajor;
	}

	public void setColorMajor(String colorMajor) {
		this.colorMajor = colorMajor;
	}



	public String getTitle() {
		return title;
	}
	
	public String getEditedTitle() {
		if (title == null || title.isEmpty())
			return "No Title!";
		else
			return title;
		
	}

	public void setTitle(String title) {
		this.title = title;
	}

	/*
	 * public void setDestinationDescription(String destinationDescription) {
	 * this.destinationDescription = destinationDescription; }
	 * 
	 * public String getDestinationDescription() { return
	 * destinationDescription; }
	 * 
	 * public void setDestinationTitle(String destinationTitle) {
	 * this.destinationTitle = destinationTitle; }
	 * 
	 * public String getDestinationTitle() { return destinationTitle; }
	 */

	@Override
	public int hashCode() {
		int hash = 0;
		hash += (id != null ? id.hashCode() : 0);
		return hash;
	}

	@Override
	public boolean equals(Object object) {
		if (!(object instanceof Guide)) {
			return false;
		}
		Guide other = (Guide) object;
		if ((this.id == null && other.id != null)
				|| (this.id != null && !this.id.equals(other.id))) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "Guide[ id=" + id + " ]";
	}

	/**
	 * Only customers and sales staff have permission to edit guides.
	 * 
	 * @param contact
	 * @return
	 */
	public boolean hasWritePermission(EWContact contact) {
		if (contact.isInGroup(EWGroup.GROUP_ADMIN))
			return true;

		if (contact.isInTeam(teamId)) {
			if (contact.isInGroup(EWGroup.GROUP_CUSTOMER))
				return true;

			if (contact.isInGroup(EWGroup.GROUP_SALES))
				return true;
		}

		return false;
	}

	public void setDestinationId(String destinationId) {
		this.destinationId = destinationId;
	}

	public String getDestinationId() {
		return destinationId;
	}

	public void setLogoFileId(Long logoFileId) {
		this.logoFileId = logoFileId;
	}

	public Long getLogoFileId() {
		return logoFileId;
	}

	public void setThumbIncrement(int thumbIncrement) {
		this.thumbIncrement = thumbIncrement;
	}

	public int getThumbIncrement() {
		return thumbIncrement;
	}

	public void incrementThumb() {
		this.thumbIncrement++;
	}

	public String getThumbName() {
		
		if(coverDesign != null)
			return coverDesign;
		
		if (thumbIncrement == 0)
			return "guide_default_thumb_1.png";

		return "guide_" + id + "_thumb_" + thumbIncrement + ".png";
	}

	public void setVisits(int visits) {
		this.visits = visits;
	}

	public int getVisits() {
		return visits;
	}

	public void setTime(int time) {
		this.time = time;
	}

	public int getTime() {
		return time;
	}

	public void setScore(int score) {
		this.score = score;
	}

	public int getScore() {
		return score;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getZipName() {
		return "guide_" + id + "_" + zipIncrement + ".zip";
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public boolean isOtherguides() {
		return otherguides;
	}

	public void setOtherguides(boolean otherguides) {
		this.otherguides = otherguides;
	}

	public int getPageviews() {
		return pageviews;
	}

	public void setPageviews(int pageviews) {
		this.pageviews = pageviews;
	}
	
	public String getSubdomain() {
		return subdomain;
	}

	public void setSubdomain(String Subdomain) {
		this.subdomain = Subdomain;
	}
	
	public String getParent() {
		return parent;
	}

	public void setParent(String Parent) {
		this.parent = Parent;
	}
	
	
	public String getCoverDesign() {
		return coverDesign;
	}

	public void setCoverDesign(String CoverDesign) {
		this.parent = coverDesign;
	}

}

trunk/beek-admin/src/main/java/co/beek/web/guide/bean/EventData.java
package co.beek.web.guide.bean;

import com.google.gdata.data.analytics.DataEntry;

public class EventData {
	private DataEntry entry;

	private String[] labelParts;

	public EventData(DataEntry entry) {
		this.entry = entry;
		labelParts = getLabel().split("\\|");
	}

	public String getCategory() {
		return entry.stringValueOf("ga:eventCategory");
	}

	public boolean isCategory(String value) {
		String c = getCategory();
		return c != null && c.indexOf(value) > -1;
	}

	public String getAction() {
		return entry.stringValueOf("ga:eventAction");
	}

	public boolean isAction(String value) {
		String c = getAction();
		return c != null && c.indexOf(value) > -1;
	}

	public String getLabel() {
		return entry.stringValueOf("ga:eventLabel");
	}

	public long getTotal() {
		return entry.longValueOf("ga:totalEvents");
	}

	public String getHotspotTitle() {
		return labelParts[0];
	}

	public String getHotspotId() {
		return labelParts[1];
	}

	public String getSceneId() {
		return labelParts[labelParts.length - 1];
	}
}

trunk/beek-admin/src/main/java/co/beek/web/guide/bean/GuideData.java
package co.beek.web.guide.bean;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

import com.google.gdata.data.analytics.DataEntry;

/**
 * query.setDimensions("ga:pagePath,ga:country,ga:city,ga:browser");
		query.setMetrics("ga:timeOnSite,ga:pageviews,ga:totalEvents");
		
 * @author danieltaylor
 *
 */
public class GuideData {
	private static Pattern GUIDE_MATCH = Pattern.compile("/g([0-9]+).*");
	private static Pattern SCENE_MATCH = Pattern.compile("/g[0-9]+/s([0-9]+).*");
	
	private DataEntry entry;
	
	private String sceneTitle;
	public String guideId;

	public GuideData(DataEntry entry) {
		this.entry = entry;
	}

	public String getPagePath() {
		return entry.stringValueOf("ga:pagePath");
	}
	
	public String getPagePathLevel1() {
		return entry.stringValueOf("ga:pagePathLevel1");
	}

	public String getGuideId() {
		Matcher matcher = GUIDE_MATCH.matcher(getPagePath());
		
		if(matcher.matches())
			return matcher.group(1);
		
		return null;
	}


	public String getCountry() {
		return entry.stringValueOf("ga:country");
	}

	public String getCity() {
		return entry.stringValueOf("ga:city");
	}
	
	public String getMonth() {
		return entry.stringValueOf("ga:month");
	}
	
	public String getVisits() {
		return entry.stringValueOf("ga:visits");
	}
	
	public String getBrowser() {
		return entry.stringValueOf("ga:browser");
	}
	
	public String getTimeOnSite() {
		return entry.stringValueOf("ga:timeOnSite");
	}
	
	public String getPageViews() {
		return entry.stringValueOf("ga:pageviews");
	}
	
	public String getPageViewsPerVisit() {
		return entry.stringValueOf("ga:pageviewsPerVisit");
	}
	
	public String getTotalEvents() {
		return entry.stringValueOf("ga:totalEvents");
	}

	public String getSceneTitle() {
		return sceneTitle;
	}

	public void setSceneTitle(String sceneTitle) {
		this.sceneTitle = sceneTitle;
	}
}

trunk/beek-admin/src/main/java/co/beek/web/guide/GuideCreateController.java
package co.beek.web.guide;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import co.beek.pano.model.dao.enterprizewizard.EWContact;
import co.beek.pano.model.dao.enterprizewizard.EWTeam;
import co.beek.pano.model.dao.entities.Destination;
import co.beek.pano.model.dao.entities.GuideDetail;
import co.beek.pano.model.dao.entities.GuideSection;
import co.beek.pano.model.dao.entities.Location;
import co.beek.pano.model.dao.entities.Scene;
import co.beek.pano.service.dataService.enterprizewizardService.EWServiceImpl;
import co.beek.pano.service.dataService.guideService.GuideService;
import co.beek.pano.service.dataService.locationService.LocationService;
import co.beek.pano.service.dataService.sceceService.SceneService;
import co.beek.util.BeekSession;
import co.beek.web.BaseController;
import co.beek.web.guide.bean.GuideSceneSelector;

@Scope("session")
@Controller("GuideCreateController")
public class GuideCreateController extends BaseController implements
		Serializable {
	private static final long serialVersionUID = -1081621548447371624L;

	@Inject
	private GuideService guideService;

	@Inject
	private LocationService locationService;

	@Inject
	private SceneService sceneService;

	private GuideDetail guide;
	
	public GuideDashboardController dashboardGuides;

	private List<Location> myLocations;

	private List<Destination> destinations;

	private List<GuideSceneSelector> selectorScenes;
	
	private String locationId;


	private Location location;
	
	public EWServiceImpl ewServiceImpl = new EWServiceImpl();

	@RequestMapping(value = "/guide/create", method = RequestMethod.GET)
	public String guideCreate() {
		return "/views/guide/create.jsf";
	}

	public List<Location> getMyLocations() {
		return myLocations;
	}

	public void setMyLocations(List<Location> myLocations) {
		this.myLocations = myLocations;
	}

	public void preRenderView() throws IOException {

		if (isPostback())
			return;

		if (redirectingToLogin())
			return;

		BeekSession session = getSession();
		EWContact contact = session.getUser();

		guide = new GuideDetail();
		guide.setTitle("New Guide");
		guide.setTeamId("CUSTOMER_1_");
		//TODO fix or take out
		//guide.setTeamId(contact.getTeams().get(0).getTeams());
		guide.setDestinationId("1");
		

		// load all destinationLocations for the logged in user
		myLocations = locationService.getAllLocations();
		Collections.reverse(myLocations);
		destinations = session.getDestinations();
		locationId = null;
		selectorScenes = new ArrayList<GuideSceneSelector>();
	}

	public List<Location> getDestinationLocations() {
		List<Location> locations = new ArrayList<Location>();
		for (Location l : myLocations)
			if (l.getDestinationId().equals(guide.getDestinationId()))
				locations.add(l);
		return locations;
	}

/*	private Location getLocation(String locationId) {
		for (Location l : myLocations)
			if (l.getId().equals(locationId))
				return l;
		return null;
	}*/

	public GuideDetail getGuide() {
		return guide;
	}

	public List<EWTeam> getTeams() {
		return getUser().getTeams();
	}

	public void setDestinations(List<Destination> destinations) {
		this.destinations = destinations;
	}

	public List<Destination> getDestinations() {
		return destinations;
	}

	public void setLocationId(String locationId) {
		this.locationId = locationId;
	}

	
	public String getLocationId() {
		return this.locationId;
	}

	public List<GuideSceneSelector> getSelectorScenes() {
		return selectorScenes;
	}

	public Location getLocation() {
		return location;
	}

	public void setLocation(Location location) {
		this.location = location;
	}



	public void saveGuide() throws IOException {

		// Save guide so we can add scenes
		if (guide.getId() == null)
			guideService.saveGuideDetail(guide);
		
		// Always add a default section to the guide
		guide.addGuideSection(GuideSection.getDefault(guide.getId()));

		if(location != null){
			List<Scene> scenes = sceneService.getAllScenesForLocation(location.getId());

			for(Scene scene : scenes)
				guide.addGuideScene(scene);
		}


		// update the guide with the new details
		guideService.saveGuideDetail(guide);
		guide.setTeamId("CUSTOMER_1_");
		guideService.saveGuideDetail(guide);
		
		BeekSession session = getSession();
		EWContact user = session.getUser();
		List<String> updateGuideID = session.getGuideID();
		updateGuideID.add(guide.getId());
		session.setGuideID(updateGuideID);
		user.setGuideID(updateGuideID);
		
		
		saveGuideToCRM();
		redirectGuideEdit(guide.getId());
		
		
	}
	

	public void doneSaveGuide() throws IOException {

		// Save guide so we can add scenes
		if (guide.getId() == null)
			guideService.saveGuideDetail(guide);
		
		// Always add a default section to the guide
		guide.addGuideSection(GuideSection.getDefault(guide.getId()));

		if(locationId != null){
			List<Scene> scenes = sceneService.getAllScenesForLocation(locationId);

			for(Scene scene : scenes)
					guide.addGuideScene(scene);
		}
		
		// update the guide with the new details
		guide.setDestinationId("1");
		guide.setTeamId("CUSTOMER_1_");
		guideService.saveGuideDetail(guide);
		
		BeekSession session = getSession();
		EWContact user = session.getUser();
		List<String> updateGuideID = session.getGuideID();
		updateGuideID.add(guide.getId());
		session.setGuideID(updateGuideID);
		user.setGuideID(updateGuideID);

		
		saveGuideToCRM();
		redirectGuideDashboard();

	}
	
	private void saveGuideToCRM()//GuideDetail guide)
	{
		try {
			ewServiceImpl.createGuide(getSession().getUsername(), getSession().getPassword(), guide);
			
			
		} catch (Exception e) {
			FacesMessage m2 = new FacesMessage(FacesMessage.SEVERITY_ERROR,
					"Hit exception", "Hit exception");
			FacesContext.getCurrentInstance().addMessage(null, m2);
		}
		
	}

	private void reloadGuide() {
		guide = guideService.getGuideDetail(guide.getId());
	}
	
	/**
	 * Used in the jsf for absolute urls back to this server
	 */
	public String getBeekDomain() {
		return getRequest().getServerName().replace("gms", "www");
	}

}

trunk/beek-admin/src/main/webapp/views/guide/create.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:c="http://java.sun.com/jsp/jstl/core"
                template="../newtemplate.xhtml">
    <ui:define name="checkurl">
	    <f:metadata>
	        <f:event listener="#{GuideCreateController.preRenderView}" 
	        		type="preRenderView"/>
	    </f:metadata>
	</ui:define>

    <ui:define name="content">
        <h:form prependId="false">
        
			<p:growl id="growl" showDetail="true" sticky="true" />

        
            <p:growl id="info" showDetail="true" autoUpdate="true"/>
                      <h:panelGrid columns="2" cellpadding="10px" >

		                      <p:panel id="locations_list" >
								  <p:selectOneListbox id="advanced" style="width: 200px" value="#{GuideCreateController.location}" converter="#{locationConverter}" var="locations" filter="true" filterMatchMode="contains">
									  <p:ajax event="valueChange" immediate="true" process="@this"/>
								  <f:selectItems value="#{GuideCreateController.myLocations}" var="location" itemLabel="#{location.title}" itemValue="#{location}" />
								  <p:column>
									  <h:outputText value="#{locations.title}" />
								  </p:column>
							  </p:selectOneListbox>


		                      </p:panel>

						  <p:panel id="next_list"  style="width: 200px; height: 200px">
							  <h:outputText value="Title: " />
	                      <p:inputText id="title_field" style="width:180px" value="#{GuideCreateController.guide.title}"/>
	                         
						<p:commandButton value="create" icon="ui-icon ui-icon-plusthick"  action="#{GuideCreateController.saveGuide}" style="margin: 50px"/>
						  </p:panel>
					  </h:panelGrid>
        </h:form>
    </ui:define>
</ui:composition>

trunk/beek-admin/src/main/webapp/views/guide/reportNoAccordion.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:c="http://java.sun.com/jsp/jstl/core"
                template="../template.xhtml">

	<ui:define name="checkurl">
	    <f:metadata>
	        <f:event listener="#{GuideReportController.preRenderView}" 
	        		type="preRenderView"/>
	    </f:metadata>
	</ui:define>
	
    <ui:define name="content">
    	<p:breadCrumb>
		<p:menuitem value="Dashboard" url="/" />
		<p:menuitem value="Guide Report" url="/guide/#{GuideReportController.guide.id}/report" />
	</p:breadCrumb>
	<style type="text/css">
	    .ui-datalist-content {
	        border:none !important;
	    }
	</style>
	 <script type='text/javascript' src='https://www.google.com/jsapi'></script>
    <script type='text/javascript'>
     google.load('visualization', '1', {'packages': ['geochart']});
     google.setOnLoadCallback(drawRegionsMap);

      function drawRegionsMap() {
        var data = google.visualization.arrayToDataTable([
        	['Country', 'Visits'],
        <ui:repeat value="${GuideReportController.countriesMapData}" var="country">
			['${country.name}', ${country.visits}],
		</ui:repeat>
        ]);

        var options = {};

        var chart = new google.visualization.GeoChart(document.getElementById('chart_div'));
        chart.draw(data, options);
    };
    </script>
	<table width="900">
		<tr>
			<td width="450" style="padding-left:50px;">
				<p:graphicImage value="#{buildProperties.cdnUrl}/#{GuideReportController.guide.thumbName}" />
			</td>
			<td width="450">
				<p:fieldset legend="Performace">
					<p:dataList value="#{GuideReportController.performance}" var="row"  >
						#{row.first}: #{row.second}
					</p:dataList> 
				</p:fieldset><br/>

				<p:fieldset legend="Engagement">
					<p:dataList value="#{GuideReportController.engagement}" var="row"  >
						#{row.first}: #{row.second}
					</p:dataList>
				</p:fieldset><br/>
				
				

				

				
			</td>
		</tr>
		<tr>
			<td>
				<p:panel header="Visits by Month" >
					<p:graphicImage value="#{GuideReportController.visitsOverTimeChart}" />
				</p:panel>
			</td>
			<td>
				<p:panel header="Average Scenes by month" >
					<p:graphicImage value="#{GuideReportController.scenesOverTimeChart}" />
				</p:panel>
			</td>
		</tr>
		<tr>
			<td>
				<p:panel header="Average Visit Duration by month" >
					<p:graphicImage value="#{GuideReportController.durationOverTimeChart}" />
				</p:panel>
			</td>
			<td>
				
			</td>
		</tr>
	</table>
	
	Scene
		<p:dataTable var="visit" value="#{GuideReportController.visitsByScene}">
			
			<p:column style="width:300px" headerText="Scene">
				<a href="#{GuideReportController.guidePath}/#{visit.sceneId}"  target="_blank">
			    	<h:outputText value="#{visit.title}" />
			    </a>
			</p:column>

			<p:column style="width:90px" headerText="Views">
			    <h:outputText value="#{visit.pageViews}" />
			</p:column>
			
			 <p:column headerText="Average visit length">
			    <h:outputText value="#{visit.avgTimeOnPage}" />
			</p:column>
			
		</p:dataTable>
		<br/>
	Referrals
		<p:dataTable var="referral" value="#{GuideReportController.referals2}">
			<p:column style="width:300px" headerText="Referral Path">
			    <a href="http://#{referral.referralSource}#{referral.referralPath}"  target="_blank">
			    	<h:outputText value="#{referral.referralSource}#{referral.referralPath}" />
			    </a>
			</p:column>

			<p:column style="width:90px" headerText="Visits">
			    <h:outputText value="#{referral.visits}" />
			</p:column>

			<p:column headerText="Pageviews per Visit">
			    <h:outputText value="#{referral.pageViewsPerVisit}" />
			</p:column>
		</p:dataTable>
	<br/>
	<br/>
		<div id="chart_div" style="width: 900px; height: 500px;"></div>
	<br/>
		<p:fieldset legend="Guide Actions">
			<p:dataList value="#{GuideReportController.guideActions}" var="row"  >
				#{row.first}: #{row.second}
			</p:dataList>
		</p:fieldset><br/>
	<br/>
	
	Media Events
		<p:dataTable var="event" value="#{GuideReportController.mediaEvents}">
			<p:column style="width:300px" headerText="Media">
				<a href="#{GuideReportController.guidePath}/#{event.sceneId}/#{event.hotspotId}"  target="_blank">
			    	<h:outputText value="#{event.hotspotTitle}" />
			    </a>
			</p:column>
			<p:column style="width:90px" headerText="Total">
			    <h:outputText value="#{event.total}" />
			</p:column>
		</p:dataTable>
    	<br/>
    	
  	Individual Visits
		<p:dataTable var="visit" value="#{GuideReportController.individualVisits}">
			<p:column style="width:300px" headerText="Email">
				<a href="/guide/#{GuideReportController.guide.id}/report/#{visit.key}/"  target="_blank">
			    	<h:outputText value="#{visit.email}" />
			    </a>
			</p:column>
			<p:column style="width:90px" headerText="Date">
			    <h:outputText value="#{event.dateFormatted}" />
			</p:column>
		</p:dataTable>
    	<br/>
	<br/>
		<br/>
	<br/>
    </ui:define>
    
</ui:composition>

trunk/beek-admin/src/main/webapp/views/guide/reportUser.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:c="http://java.sun.com/jsp/jstl/core"
                template="../newtemplate.xhtml">

	<ui:define name="checkurl">
	    <f:metadata>
	        <f:event listener="#{GuideReportUserController.preRenderView}" 
	        		type="preRenderView"/>
	    </f:metadata>
	</ui:define>
	
	<ui:param name="visit" value="#{GuideReportUserController.visitData}" />
	
    <ui:define name="content">
    	<p:breadCrumb>
		<p:menuitem value="Dashboard" url="/" />
		<p:menuitem value="Guide Report" url="/guide/#{GuideReportUserController.guide.id}/report" />
		<p:menuitem value="User" url="/guide/#{GuideReportUserController.guide.id}/report/#{GuideReportUserController.guide.id}" />
	</p:breadCrumb>
	<style type="text/css">
	    .ui-datalist-content {
	        border:none !important;
	    }
	</style>
	<br/><br/>
		<p:fieldset legend="Details" style="width: 200px; float: left">
				country: #{visit.country}<br/>
				city: #{visit.city}<br/>
				browser: #{visit.browser}<br/>
		</p:fieldset><br/>
		
				<p:fieldset legend="Statistics" style="width: 200px; float: right">
				Visits: #{visit.visits}<br/>
				Active Visits: #{visit.visitsWithEvent}<br/>
				Total Time: #{visit.timeOnSite}<br/>
		</p:fieldset><br/>
		
		<br/><br/><br/><br/><br/><br/>
		Scenes
		<p:dataTable var="v" value="#{GuideReportUserController.visits}">
			<p:column style="width:90px" headerText="Scene Title">
			    <h:outputText value="#{v.sceneTitle}" />
			</p:column>
			<p:column style="width:90px" headerText="Page Views">
			    <h:outputText value="#{v.pageViews}" />
			</p:column>
		</p:dataTable>
    	<br/>
		
		Events
		<p:dataTable var="event" value="#{GuideReportUserController.events}">
			<p:column style="width:90px" sortBy="#{event.category}" headerText="Category">
			    <h:outputText value="#{event.category}" />
			</p:column>
			<p:column style="width:90px" sortBy="#{event.action}" headerText="Action">
			    <h:outputText value="#{event.action}" />
			</p:column>
			<p:column style="width:90px" headerText="Scene Title">
			    <h:outputText value="#{event.sceneTitle}" />
			</p:column>
			<p:column style="width:90px" headerText="Hotspot Title">
			    <h:outputText value="#{event.hotspotTitle}" />
			</p:column>
		</p:dataTable>
    	<br/>
    </ui:define>
    
</ui:composition>